In [5]:
# Import dependences.
from pathlib import Path
import math
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import sklearn.preprocessing as preproc
import matplotlib.pyplot as plt

In [6]:
# imp csv...from desktop only, practice
house_df = pd.read_csv('/Users/tanyaczeban/Desktop/All_DATA-PROV.csv') #, parse_dates=[year], index_col='year')
house_df

,Provinces,year,House Prices,Kilotonnes,Crime/100000,Immigration Totals,Med Imm Wages,Household Income,Population,Ed Institutions
0,Newfoundland,2015,299300,"11,299",6370.75,390,"35,200",341412,"2,113,237",7
1,Newfoundland,2016,298800,"11,636",6500.63,345,"40,700",342472,"2,117,189",7
2,Newfoundland,2017,294900,"11,505",6042.04,285,"45,600",343966,"2,114,428",7
3,Newfoundland,2018,285000,"11,337",6041.56,300,"45,100",346836,"2,105,228",7
4,Newfoundland,2019,272700,"11,277",6686.65,300,"47,100",349654,"2,096,208",7
...,...,...,...,...,...,...,...,...,...,...
96,BC,2015,610000,"80,171",8608.09,"33,105","28,800",346298,"19,082,570",63
97,BC,2016,717600,"80,291",8488.51,"33,290","30,700",351579,"19,386,872",63
98,BC,2017,775400,"81,521",8090.02,"33,495","32,500",362511,"19,681,992",63
99,BC,2018,816300,"83,054",8250.95,"33,725","34,400",368048,"20,001,433",63
100,BC,2019,785500,"83,628",9573.92,"33,975","36,400",384468,"20,339,311",63

In [8]:
# drop rows not related to the results....my dataset had these rows removed already
#house_df = df.drop(labels=[0,1,2,3,4],axis=0)
#house_df.head()

In [9]:
# Change the index to "year".
house_df.set_index("year", inplace=True)
house_df.head()

,Provinces,House Prices,Kilotonnes,Crime/100000,Immigration Totals,Med Imm Wages,Household Income,Population,Ed Institutions
year,,,,,,,,,
2015,Newfoundland,299300,"11,299",6370.75,390,"35,200",341412,"2,113,237",7
2016,Newfoundland,298800,"11,636",6500.63,345,"40,700",342472,"2,117,189",7
2017,Newfoundland,294900,"11,505",6042.04,285,"45,600",343966,"2,114,428",7
2018,Newfoundland,285000,"11,337",6041.56,300,"45,100",346836,"2,105,228",7
2019,Newfoundland,272700,"11,277",6686.65,300,"47,100",349654,"2,096,208",7

In [10]:
#parse year
house_df.parse_year = ['year']
house_df

/Users/tanyaczeban/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  """Entry point for launching an IPython kernel.

,Provinces,House Prices,Kilotonnes,Crime/100000,Immigration Totals,Med Imm Wages,Household Income,Population,Ed Institutions
year,,,,,,,,,
2015,Newfoundland,299300,"11,299",6370.75,390,"35,200",341412,"2,113,237",7
2016,Newfoundland,298800,"11,636",6500.63,345,"40,700",342472,"2,117,189",7
2017,Newfoundland,294900,"11,505",6042.04,285,"45,600",343966,"2,114,428",7
2018,Newfoundland,285000,"11,337",6041.56,300,"45,100",346836,"2,105,228",7
2019,Newfoundland,272700,"11,277",6686.65,300,"47,100",349654,"2,096,208",7
...,...,...,...,...,...,...,...,...,...
2015,BC,610000,"80,171",8608.09,"33,105","28,800",346298,"19,082,570",63
2016,BC,717600,"80,291",8488.51,"33,290","30,700",351579,"19,386,872",63
2017,BC,775400,"81,521",8090.02,"33,495","32,500",362511,"19,681,992",63
2018,BC,816300,"83,054",8250.95,"33,725","34,400",368048,"20,001,433",63
2019,BC,785500,"83,628",9573.92,"33,975","36,400",384468,"20,339,311",63

In [25]:
# Check any null value and data type.
house_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 101 entries, 2015 to 2019
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Provinces           101 non-null    object
 1   House Prices        100 non-null    object
 2   Kilotonnes          100 non-null    object
 3   Crime/100000        100 non-null    object
 4   Immigration Totals  100 non-null    object
 5   Med Imm Wages       100 non-null    object
 6   Household Income    100 non-null    object
 7   Population          100 non-null    object
 8   Ed Institutions     100 non-null    object
dtypes: object(9)
memory usage: 7.9+ KB

In [27]:
#count
house_df.Provinces.value_counts()

Newfoundland     10
PEI              10
Nova Scotia      10
New Brunswick    10
Quebec           10
Ontario          10
Manitoba         10
Saskatchewan     10
Alberta          10
BC                9
=======           1
ï»¿Provinces        1
Name: Provinces, dtype: int64

In [37]:
#rename
house_df.rename(columns={'Provinces':'province'}, inplace = True)
house_df

,House Prices,Kilotonnes,Crime/100000,Immigration Totals,Med Imm Wages,Household Income,Population,Ed Institutions,Alberta_province,BritishColumbia_province,Manitoba_province,NewBrunswick_province,Newfoundland_and_Labrador_province,NovaScotia_province,Ontario_province,PrinceEdwardIsland_province,Quebec_province,Saskatchewan_province
year,,,,,,,,,,,,,,,,,,
2015,299300,"11,299",6370.75,390,"35,200",341412,"2,113,237",7,0,0,0,0,1,0,0,0,0,0
2016,298800,"11,636",6500.63,345,"40,700",342472,"2,117,189",7,0,0,0,0,1,0,0,0,0,0
2017,294900,"11,505",6042.04,285,"45,600",343966,"2,114,428",7,0,0,0,0,1,0,0,0,0,0
2018,285000,"11,337",6041.56,300,"45,100",346836,"2,105,228",7,0,0,0,0,1,0,0,0,0,0
2019,272700,"11,277",6686.65,300,"47,100",349654,"2,096,208",7,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015,610000,"80,171",8608.09,"33,105","28,800",346298,"19,082,570",63,0,1,0,0,0,0,0,0,0,0
2016,717600,"80,291",8488.51,"33,290","30,700",351579,"19,386,872",63,0,1,0,0,0,0,0,0,0,0
2017,775400,"81,521",8090.02,"33,495","32,500",362511,"19,681,992",63,0,1,0,0,0,0,0,0,0,0
2018,816300,"83,054",8250.95,"33,725","34,400",368048,"20,001,433",63,0,1,0,0,0,0,0,0,0,0
2019,785500,"83,628",9573.92,"33,975","36,400",384468,"20,339,311",63,0,1,0,0,0,0,0,0,0,0

In [51]:
#only keep year/houseprice/province
new_house_df = house_df.drop(columns = ['Kilotonnes','Crime/100000','Immigration Totals','Med Imm Wages','Household Income','Population','Ed Institutions'])
new_house_df

,House Prices,Alberta_province,BritishColumbia_province,Manitoba_province,NewBrunswick_province,Newfoundland_and_Labrador_province,NovaScotia_province,Ontario_province,PrinceEdwardIsland_province,Quebec_province,Saskatchewan_province,New House Prices
year,,,,,,,,,,,,
2015,299300,0,0,0,0,1,0,0,0,0,0,NaN
2016,298800,0,0,0,0,1,0,0,0,0,0,299300
2017,294900,0,0,0,0,1,0,0,0,0,0,298800
2018,285000,0,0,0,0,1,0,0,0,0,0,294900
2019,272700,0,0,0,0,1,0,0,0,0,0,285000
...,...,...,...,...,...,...,...,...,...,...,...,...
2015,610000,0,1,0,0,0,0,0,0,0,0,420900
2016,717600,0,1,0,0,0,0,0,0,0,0,610000
2017,775400,0,1,0,0,0,0,0,0,0,0,717600
2018,816300,0,1,0,0,0,0,0,0,0,0,775400
2019,785500,0,1,0,0,0,0,0,0,0,0,816300

In [52]:
#shift so data #'s move 1 year up (ie 2015 goes to 2016... New House Prices in last col)'
new_house_df['New House Prices'] = house_df['House Prices'].shift(1)
new_house_df

,House Prices,Alberta_province,BritishColumbia_province,Manitoba_province,NewBrunswick_province,Newfoundland_and_Labrador_province,NovaScotia_province,Ontario_province,PrinceEdwardIsland_province,Quebec_province,Saskatchewan_province,New House Prices
year,,,,,,,,,,,,
2015,299300,0,0,0,0,1,0,0,0,0,0,NaN
2016,298800,0,0,0,0,1,0,0,0,0,0,299300
2017,294900,0,0,0,0,1,0,0,0,0,0,298800
2018,285000,0,0,0,0,1,0,0,0,0,0,294900
2019,272700,0,0,0,0,1,0,0,0,0,0,285000
...,...,...,...,...,...,...,...,...,...,...,...,...
2015,610000,0,1,0,0,0,0,0,0,0,0,420900
2016,717600,0,1,0,0,0,0,0,0,0,0,610000
2017,775400,0,1,0,0,0,0,0,0,0,0,717600
2018,816300,0,1,0,0,0,0,0,0,0,0,775400
2019,785500,0,1,0,0,0,0,0,0,0,0,816300

In [42]:
# Creating dummy variables for provinces
house_df['Alberta_province'] = np.where(house_df["province"]=='Alberta', 1, 0)
house_df['BritishColumbia_province'] = np.where(house_df["province"]=='BC', 1, 0)
house_df['Manitoba_province'] = np.where(house_df['province']=='Manitoba', 1, 0)
house_df['NewBrunswick_province'] = np.where(house_df['province']=='New Brunswick', 1, 0)
house_df['Newfoundland_and_Labrador_province'] = np.where(house_df['province']=='Newfoundland', 1, 0)
house_df['NovaScotia_province'] = np.where(house_df['province']=='Nova Scotia', 1, 0)
house_df['Ontario_province'] = np.where(house_df['province']=='Ontario', 1,0)
house_df['PrinceEdwardIsland_province'] = np.where(house_df['province']=='PEI', 1, 0)
house_df['Quebec_province'] = np.where(house_df['province']=='Quebec', 1, 0)
house_df['Saskatchewan_province'] = np.where(house_df['province']=='Saskatchewan', 1, 0)

# Dropping original column state
house_df.drop(columns=['province'], axis=1, inplace=True)

KeyError: 'province'