In [12]:
%matplotlib inline
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import tensorflow as tf
import numpy as np
from sklearn.model_selection import train_test_split
import sklearn.preprocessing as preproc
import matplotlib.pyplot as plt

# 1. Preprocess

In [13]:
# Import data from database and set index on the first column
house_df = pd.read_csv('Resources/mockdata.csv',index_col=0)
house_df.head()

,Year,Household Income,CRIM,flowgreenhouse_emmissions,Provincial Population,number of college,House price
Province,,,,,,,
Alberta,2015,108594.0,8916.56,"278,925","16,548,357",52,432.8
British Columbia,2015,79234.0,8608.09,"80,171","19,082,570",63,610.0
Manitoba,2015,72971.0,8925.91,"20,876","5,164,103",28,283.0
New Brunswick,2015,63767.0,5478.74,"17,835","3,037,185",17,199.8
Newfoundland and Labrador,2015,75183.0,6370.75,"11,299","2,113,237",7,299.3

In [16]:
house_df

,Year,Household Income,CRIM,flowgreenhouse_emmissions,Provincial Population,number of college,House price
Province,,,,,,,
Alberta,2015,108594.0,8916.56,"278,925","16,548,357",52,432.8
British Columbia,2015,79234.0,8608.09,"80,171","19,082,570",63,610.0
Manitoba,2015,72971.0,8925.91,"20,876","5,164,103",28,283.0
New Brunswick,2015,63767.0,5478.74,"17,835","3,037,185",17,199.8
Newfoundland and Labrador,2015,75183.0,6370.75,"11,299","2,113,237",7,299.3
Nova Scotia,2015,64717.0,5727.24,"17,797","3,749,412",13,256.1
Ontario,2015,79674.0,4021.58,"168,636","54,792,403",201,455.0
Prince Edward Island,2015,63660.0,4750.04,"1,584","578,067",4,204.2
Quebec,2015,61161.0,4252.49,"90,142","32,691,481",229,305.8
Saskatchewan,2015,83814.0,"12,919.20","76,312","4,482,873",36,332.6

In [18]:
# check null value and data type.
house_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, Alberta  to Saskatchewan
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Year                       10 non-null     int64
 1   Household Income           10 non-null     float64
 2   CRIM                       10 non-null     object
 3   flowgreenhouse_emmissions  10 non-null     object
 4   Provincial Population      10 non-null     object
 5   number of college          10 non-null     int64
 6   House price                10 non-null     float64
dtypes: float64(2), int64(2), object(3)
memory usage: 640.0+ bytes

In [19]:
house_df.describe()

         Year  Household Income  number of college  House price
count    10.0         10.000000          10.000000     10.00000
mean   2015.0      75277.500000          65.000000    337.86000
std       0.0      14147.754555          81.559794    127.34809
min    2015.0      61161.000000           4.000000    199.80000
25%    2015.0      64004.500000          14.000000    262.82500
50%    2015.0      74077.000000          32.000000    302.55000
75%    2015.0      79564.000000          60.250000    407.75000
max    2015.0     108594.000000         229.000000    610.00000

In [5]:
# change the data type
# house_df["Household_Income","flowgreenhouse_emmissions","Provincial_Population"].astype(dtype='float')

In [6]:
# house_df.hist(bins=50,figsize=(20,15))
# plt.show()

In [7]:
# house_df.drop('province',axis=1)
#X = pd.get_dummies(house_df.drop("House price", axis=1))
#y  = house_df["House price"]
#X.describe()

In [8]:
# Creating the scaler instance
from sklearn.preprocessing import MinMaxScaler
data_scaler = MinMaxScaler()

In [9]:
# Fitting the scaler （divide）

In [10]:
# create correlation matrix 
corr_matrix=house_df.corr()
corr_matrix["House price"].sort_values(ascending=False)

House price          1.000000
Household Income     0.573413
number of college    0.346018
Year                      NaN
Name: House price, dtype: float64

In [11]:
plt.scatter(house_df['flowgreenhouse_emmissions'], house_df['House Price'], color='red')
plt.title('flowgreenhouse_emmissions Vs House Price', fontsize=14)
plt.xlabel('flowgreenhouse_emmissions', fontsize=14)
plt.ylabel('House Price', fontsize=14)
plt.grid(True)
plt.show()

KeyError: 'House Price'